services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
  backend:
    build: ./backend
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - database
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: jobreadiness
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
